language: php
php:
  - '7.0'
  - '7.1'
  - nightly
services:
  - mysql

install:
  - composer install --prefer-dist

script:
  - php bin/entity gen resources/tests/entities.json
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter
