<?php
declare(strict_types = 1);

namespace mheinzerling\entity\orm;

use mheinzerling\commons\database\ConnectionProvider;
use mheinzerling\commons\database\TestDatabaseConnection;
use mheinzerling\test2\User;
use mheinzerling\test2\UserRepository;
use mheinzerling\TestModel;

class EntityTest extends \PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $pdo = new TestDatabaseConnection(true);
        ConnectionProvider::set($pdo);
        TestModel::getDatabase()->setName($pdo->getDatabaseName());
        TestModel::initialize($pdo, false);

    }


    public function testFetchAllEmpty()
    {
        $repo = new UserRepository();
        static::assertEquals([], $repo->fetchAll());
    }

    public function testPersistFetchAll()
    {
        $repo = new UserRepository();
        $foo = new User();
        $foo->setNick("foo");
        $foo->setBirthday(new \DateTime("2016-02-03"));
        $bar = new User();
        $bar->setNick("bar");
        $repo->persist($foo);
        $repo->persist($bar); //TODO

        static::assertEquals([$foo, $bar], $repo->fetchAll());
    }

    public function testFetchUserById()
    {
        $repo = new UserRepository();
        $foo = new User();
        $foo->setNick("foo");
        $foo->setBirthday(new \DateTime());
        $repo->persist($foo);

        $bar = new User();
        $bar->setNick("bar");
        $repo->persist($bar);

        static::assertEquals($bar, $repo->fetchById($bar->getId()));
    }
}